<x-app-layout>
    <section class="dark:bg-jacarta-800 relative py-16 md:py-24">
        <picture class="pointer-events-none absolute inset-0 -z-10 dark:hidden">
            <img src="img/gradient_light.jpg" alt="gradient" class="h-full w-full" />
        </picture>
        <div class="container">
            <h1 class="font-display text-jacarta-700 text-center text-4xl font-bold dark:text-white">
                Disclaimer
            </h1>
            <div class="article-content mx-auto max-w-[48.125rem] space-y-4">
                <h2 class="text-base py-4 font-semibold">Updated at 2022-01-01</h2>

                <p>Amaris hereby grants you access to https://amaris.ng/ (“the Website”) and invites you to purchase the services offered here.</p>

                <h2 class="text-2xl sm:text-3xl font-bold pt-8">Definitions and key terms</h2>
                <p>
                    To help explain things as clearly as possible in this Disclaimer, every time any of these terms are referenced, are strictly defined as:
                </p>
                <div class="pl-0 sm:pl-4">
                    <ul>
                        <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>

                        <li><strong>Company:</strong> when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Amaris Synergy Limited, 15, yusuf street, oke ira, ogba, Lagos that is responsible for your information under this Disclaimer.</li>

                        <li><strong>Service:</strong> refers to the service provided by Amaris as described in the relative terms (if available) and on this platform.</li>

                        <li><strong>Website:</strong> Amaris."’s" site, which can be accessed via this URL: https://amaris.ng/</li>
                        <li><strong>You:</strong> a person or entity that is registered with Amaris to use the Services.</li>
                    </ul>
                </div>

                <h2 class="text-2xl sm:text-3xl font-bold pt-8">Limited liability</h2>
                <p>Amaris endeavours to update and/or supplement the content of the website on a regular basis. Despite our care and attention, content may be incomplete and/or incorrect.</p>

                <p>The materials offered on the website are offered without any form of guarantee or claim to their correctness. These materials can be changed at any time without prior notice from Amaris.</p>

                <p>Particularly, all prices on the website are stated subject to typing and programming errors. No liability is assumed for the implications of such errors. No agreement is concluded on the basis of such errors.</p>

                <p>Amaris shall not bear any liability for hyperlinks to websites or services of third parties included on the website. From our website, you can visit other websites by following hyperlinks to such external sites. While we strive to provide only quality links to useful and ethical websites, we have no control over the content and nature of these sites. These links to other websites do not imply a recommendation for all the content found on these sites. Site owners and content may change without notice and may occur before we have the opportunity to remove a link which may have gone ‘bad’.</p>

                <p>Please be also aware that when you leave our website, other sites may have different privacy policies and terms which are beyond our control. Please be sure to check the Privacy Policies of these sites as well as their "Terms of Service" before engaging in any business or uploading any information.
                </p>


                <h2 class="text-2xl sm:text-3xl font-bold pt-2">Links to Other Websites Disclaimer</h2>
                <p>This Disclaimer applies only to the Services. The Services may contain links to other websites not operated or controlled by Amaris. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website,including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy and Terms of every site You visit.
                </p>
                <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

                <h2 class="text-2xl sm:text-3xl font-bold pt-2">Errors and Omissions Disclaimer</h2>
                <p>
                    Amaris is not responsible for any content, code or any other imprecision.
                </p>
                <p>Amaris does not provide warranties or guarantees.</p>
                <p>In no event shall Amaris be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. Amaris reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.</p>

                <h2 class="text-2xl sm:text-3xl font-bold pt-8">General Disclaimer</h2>
                <p>
                    The Amaris Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether express or implied. Amaris is a distributor and not a publisher of the content supplied by third parties; as such, Amaris exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via the Amaris Service. Without limiting the foregoing, Amaris specifically disclaims all warranties and representations in any content transmitted on or in connection with the Amaris Service or on sites that may appear as links on the Amaris Service, or in the products provided as a
                    part of, or otherwise in connection with, the Amaris Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by Amaris or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, Amaris does not warrant that the Amaris Service will be uninterrupted, uncorrupted, timely, or error-free.
                </p>

                <h2 class="text-2xl sm:text-3xl font-bold pt-8">Educational Disclosure</h2>
                <p>Any Information provided by Amaris is for educational purposes only, and is not to be interpreted as a recommendation for a specific treatment plan, product, or course of action. Amaris is a distributor and not a publisher of the content supplied by third parties; as such, Amaris exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information or educational content provided through or accessible via Amaris. Without limiting the foregoing, Amaris specifically disclaims all warranties and representations in any content transmitted on or in connection with Amaris or on sites that may appear as links on Amaris, or in the products provided as a part of, or otherwise in connection with, the Amaris. No oral advice or written information given by Amaris or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty.</p>

                <h2 class="text-2xl sm:text-3xl font-bold pt-8">Your Consent</h2>
                <p>We've updated our Disclaimer to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Disclaimer and agree to its terms.</p>

                <h2 class="text-2xl sm:text-3xl font-bold pt-8">Changes To Our Disclaimer</h2>
                <p>Should we update, amend or make any changes to this document so that they accurately reflect our Service and policies. Unless otherwise required by law, those changes will be prominently posted here. Then, if you continue to use the Service, you will be bound by the updated Disclaimer. If you do not want to agree to this or any updated Disclaimer, you can delete your account.</p>

                <h2 class="text-2xl sm:text-3xl font-bold pt-8">Contact Us</h2>
                <p>
                    Don't hesitate to contact us if you have any questions regarding this Disclaimer.
                </p>
                <ul class="leading-relaxed">
                    <li> - Via Email:  contact@amaris.ng </li>
                </ul>
            </div>
        </div>
    </section>
    <!-- end TOS -->
</x-app-layout>
