<x-app-layout>
    <section class="dark:bg-jacarta-800 relative py-16 md:py-24">
        <picture class="pointer-events-none absolute inset-0 -z-10 dark:hidden">
            <img src="img/gradient_light.jpg" alt="gradient" class="h-full w-full" />
        </picture>
        <div class="container">
            <h1 class="font-display text-jacarta-700 text-center text-4xl font-bold dark:text-white">
                Privacy Policy
            </h1>
            <div class="article-content mx-auto max-w-[48.125rem] space-y-4">
                <h2 class="text-base py-4 font-semibold">Updated at 2022-01-01</h2>

                <p>
                    Amaris (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy explains how your personal information
                    is collected, used, and disclosed by Amaris.
                </p>
                <p>
                    This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”) alongside our application,
                    Amaris. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage,
                    use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
                </p>

                <h2 class="text-3xl font-extrabold pt-8">Definitions and key terms</h2>
                <p>
                    To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly
                    defined as:
                </p>
                <div class="pl-0 sm:pl-4">
                    <ul>
                        <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser,
                        provide analytics, remember information about you such as your language preference or login information.</li>
                        <li><strong>Company:</strong> when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Amaris Synergy Limited, 15, yusuf street, oke ira, ogba, Lagos. that is responsible for your information under this Privacy Policy.</li>
                        <li><strong>Country:</strong> where Amaris or the owners/founders of Amaris are based, in this case is Nigeria</li>
                        <li><strong>Customer:</strong> refers to the company, organization or person that signs up to use the Amaris Service to manage the relationships with your consumers or service users.</li>
                        <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Amaris and use the services.</li>
                        <li><strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address.
                        These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
                        <li><strong>Personnel:</strong> refers to those individuals who are employed by Amaris or are under contract to perform a service on behalf of one of the parties.</li>
                        <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
                        <li><strong>Service:</strong> refers to the service provided by Amaris as described in the relative terms (if available) and on this platform.</li>
                        <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
                        <li><strong>Website:</strong> Amaris's site, which can be accessed via this URL: https://amaris.ng/</li>
                        <li><strong>You:</strong> a person or entity that is registered with Amaris to use the Services.</li>
                    </ul>
                </div>

                <h2 class="text-3xl font-extrabold pt-8">What Information Do We Collect?</h2>
                <p>
                    We collect information from you when you visit our website, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.
                </p>
                <div class="pl-0 sm:pl-4">
                    <ul class="font-semibold list-disc ml-4">
                        <li>Name / Username</li>
                        <li>Phone Numbers</li>
                        <li>Email Addresses</li>
                        <li>Billing Addresses</li>
                        <li>Debit/credit card numbers</li>
                        <li>Age</li>
                        <li>Password</li>
                    </ul>
                </div>

                <h2 class="text-3xl font-extrabold pt-8">When does Amaris use end user information from third
                    parties?</h2>
                <p>
                    Amaris will collect End User Data necessary to provide the Amaris services to our customers.
                </p>
                <p>
                    End users may voluntarily provide us with information they have made available on social media websites. If you provide us with any such information, we may collect publicly available information from the social media websites you have indicated. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.
                </p>


                <h2 class="text-3xl font-extrabold pt-8">When does Amaris use customer information from third parties?</h2>
                <p>
                    We receive some information from the third parties when you contact us. For example, when you submit your email address to
                    us to show interest in becoming a Amaris customer, we receive information from a third party that provides automated fraud
                    detection services to Amaris. We also occasionally collect information that is made publicly available on social media websites.
                    You can control how much of your information social media websites make public by visiting these websites and changing your
                    privacy settings
                </p>

                <h2 class="text-3xl font-extrabold pt-8">Do we share the information we collect with third parties?</h2>
                <p>
                    We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.
                </p>
                <p>
                    We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and
                    maintaining our servers and the website, database storage and management, e-mail management, storage marketing, credit
                    card processing, customer service and fulfilling orders for products and services you may purchase through the website. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.
                </p>
                <p>
                    We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as webanalytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general
                    location and other technographics such as connection speed, whether you have visited the website in a shared location, and
                    type of the device used to visit the website. They may aggregate information about our advertising and what you see on the
                    website and then provide auditing, research and reporting for us and our advertisers. We may also disclose personal and
                    non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations.
                </p>

                <h2 class="text-3xl font-extrabold pt-8">Where and when is information collected from customers and end users?</h2>
                <p>
                    Amaris will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above.
                </p>

                <h2 class="text-3xl font-extrabold pt-8">How Do We Use Your Email Address?</h2>
                <p>
                    By submitting your email address on this website, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy.</p>
                <p>
                    <strong>Note:</strong> If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.
                </p>

                <h2 class="text-3xl font-extrabold pt-8">How Long Do We Keep Your Information?</h2>
                <p>
                    We keep your information only so long as we need it to provide Amaris to you and fulfill the purposes described in this policy.
                </p>
                <p>
                    This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we’ll either remove it from our systems or depersonalize it so that we can't identify you.</p>

                <h2 class="text-3xl font-extrabold pt-8">How Do We Protect Your Information?</h2>
                <p>
                    We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to Amaris or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.
                </p>



            </div>
        </div>
    </section>
    <!-- end TOS -->
</x-app-layout>
