<x-app-layout>
    <section class="dark:bg-jacarta-800 relative py-16 md:py-24">
        <picture class="pointer-events-none absolute inset-0 -z-10 dark:hidden">
            <img src="img/gradient_light.jpg" alt="gradient" class="h-full w-full" />
        </picture>
        <div class="container">
            <h1 class="font-display text-jacarta-700 text-center text-4xl font-bold dark:text-white">
                Return & Refund Policy
            </h1>
            <div class="article-content mx-auto max-w-[48.125rem] space-y-4">
                <h2 class="text-base py-4 font-semibold">Updated at 2022-01-01</h2>

                <h2 class="text-3xl font-extrabold pt-8">Definitions and key terms</h2>
                <p>
                    To help explain things as clearly as possible in this Return & Refund Policy, every time any of these terms are referenced, are
                    strictly defined as:
                </p>
                <div class="pl-0 sm:pl-4">
                    <ul>
                        <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser,
                        provide analytics, remember information about you such as your language preference or login information.</li>
                        <li><strong>Company:</strong> when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Amaris Synergy Limited, 15, yusuf street, oke ira, ogba, Lagos. that is responsible for your information under this Return & Refund Policy.</li>

                        <li><strong>Customer:</strong> refers to the company, organization or person that signs up to use the Amaris Service to manage the relationships with your consumers or service users.</li>
                        <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Amaris and use the services</li>

                        <li><strong>Service:</strong> refers to the service provided by Amaris as described in the relative terms (if available) and on this platform.</li>
                        <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
                        <li><strong>Website:</strong> Amaris."’s" site, which can be accessed via this URL: https://amaris.ng/</li>
                        <li><strong>You:</strong> a person or entity that is registered with Amaris to use the Services.</li>
                    </ul>
                </div>

                <h2 class="text-3xl font-extrabold pt-8">Return & Refund Policy</h2>
                <p>
                    Thanks for shopping at Amaris. We appreciate the fact that you like to buy the stuff we build. We also want to make sure you
                    have a rewarding experience while you’re exploring, evaluating, and purchasing our products.
                </p>
                <p>
                    As with any shopping experience, there are terms and conditions that apply to transactions at Amaris. We’ll be as brief as our
                    attorneys will allow. The main thing to remember is that by placing an order or making a purchase at Amaris, you agree to the
                    terms set forth below along with Policy.
                </p>
                <p>
                    If there’s something wrong with the product/service you bought, or if you are not happy with it, you have 1 week to issue a
                    refund and return your product/service.
                </p>
                <p>
                    If you would like to return a product, the only way would be if you follow the next guidelines:
                </p>


                <h2 class="text-3xl font-extrabold pt-8">Refunds</h2>
                <p>
                    We at ourselves to serving our customers with the best products. Every single product that you choose is thoroughly inspected,
                    checked for defects and packaged with utmost care. We do this to ensure that you fall in love with our products.
                </p>
                <p>
                    Sadly, there are times when we may not have the product(s) that you choose in stock, or may face some issues with our
                    inventory and quality check. In such cases, we may have to cancel your order. You will be intimated about it in advance so that
                    you don't have to worry unnecessarily about your order. If you have purchased via Online payment (not Cash on Delivery), then
                    you will be refunded once our team confirms your request.
                </p>
                <p>
                    We carry out thorough quality check before processing the ordered item. We take utmost care while packing the product. At thesame time we ensure that the packing is good such that the items won’t get damaged during transit. Please note that Amaris is
                    not liable for damages that are caused to the items during transit or transportation.
                </p>
                <p>
                    We will revise your returned product as soon as we receive it and if it follows the guidelines addressed above, we will proceed to issue a refund of your purchase. Your refund may take a couple of days to process but you will be notified when you receive your money
                </p>


                <h2 class="text-3xl font-extrabold pt-8">Shipping</h2>
                <p>
                    Amaris is not responsible for return shipping costs. Every shipping has to be paid by the customer, even if the item had free
                    shipping in the first place, the customer has to pay for the shipping in return.
                </p>

                <h2 class="text-3xl font-extrabold pt-8">Your Consent</h2>
                <p>
                    By using our website, registering an account, or making a purchase, you hereby consent to our Return & Refund Policy and
                    agree to its terms.
                </p>

                <h2 class="text-3xl font-extrabold pt-8">Changes To Our Return & Refund Policy</h2>
                <p>Should we update, amend or make any changes to this document so that they accurately reflect our Service and policies.</p>
                <p>
                    Unless otherwise required by law, those changes will be prominently posted here. Then, if you continue to use the Service, you
                    will be bound by the updated Return & Refund Policy. If you do not want to agree to this or any updated Return & Refund Policy,
                    you can delete your account.
                </p>



                <h2 class="text-3xl font-extrabold pt-8">Contact Us</h2>
                <p>
                    If, for any reason, You are not completely satisfied with any good or service that we provide, don't hesitate to contact us and we will discuss any of the issues you are going through with our product.
                </p>
                <ul class="list-disc">
                    <li>Via Email: contact@amaris.ng</li>
                </ul>

            </div>
        </div>
    </section>
    <!-- end TOS -->
</x-app-layout>
