<x-app-layout>
    <section class="dark:bg-jacarta-800 relative py-16 md:py-24">
        <picture class="pointer-events-none absolute inset-0 -z-10 dark:hidden">
            <img src="img/gradient_light.jpg" alt="gradient" class="h-full w-full" />
        </picture>
        <div class="container">
            <h1 class="font-display text-jacarta-700 text-center text-4xl font-bold dark:text-white">
                Terms & Conditions
            </h1>
            <div class="article-content mx-auto max-w-[48.125rem] space-y-4">
                <h2 class="text-base">Updated at 2022-01-01</h2>

                <h2 class="text-3xl font-bold">General Terms</h2>
                <p>
                    By accessing and placing an order with Amaris, you confirm that you are in agreement with and bound by the terms of service
                    contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of
                    communication between you and Amaris.
                </p>
                <p>
                    Under no circumstances shall Amaris team be liable for any direct, indirect, special, incidental or consequential damages,
                    including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if
                    Amaris team or an authorized representative has been advised of the possibility of such damages. If your use of materials from
                    this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.
                </p>
                <p>
                    Amaris will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the
                    rights to change prices and revise the resources usage policy in any moment.
                </p>

                <h2 class="text-3xl font-extrabold">License</h2>

                <p>
                    Amaris grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly
                    in accordance with the terms of this Agreement.
                </p>

                <p>
                    These Terms & Conditions are a contract between you and Amaris (referred to in these Terms & Conditions as "Amaris", "us",
                    "we" or "our"), the provider of the Amaris website and the services accessible from the Amaris website (which are collectively
                    referred to in these Terms & Conditions as the "Amaris Service").
                </p>
                <p>
                    You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use
                    the Amaris Service. In these Terms & Conditions, "you" refers both to you as an individual and to the entity you represent. If you
                    violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account without
                    notice.
                </p>

                <h2 class="text-3xl font-extrabold mt-4">Definitions and key terms</h2>
                <p>
                    To help explain things as clearly as possible in this Terms & Conditions, every time any of these terms are referenced, are
                    strictly defined as:
                </p>
                <div class="pl-0 sm:pl-4">
                    <ul>
                        <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser,
                            provide analytics, remember information about you such as your language preference or login information.</li>
                        <li><strong>Company:</strong> when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Amaris Synergy Limited, 15, yusuf street,
                            oke ira, ogba, Lagos that is responsible for your information under this Terms & Conditions.</li>
                        <li><strong>Country: </strong> where Amaris or the owners/founders of Amaris are based, in this case is Nigeria</li>

                        <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Amaris and use the services.</li>
                        <li><strong>Service:</strong> refers to the service provided by Amaris as described in the relative terms (if available) and on this platform.</li>
                        <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
                        <li><strong>Website:</strong> Amaris."’s" site, which can be accessed via this URL: <a
                                href="https://amaris.ng/">https://amaris.ng/</a></li>
                        <li><strong>You:</strong> a person or entity that is registered with Amaris to use the Services.</li>
                    </ul>
                </div>

                <h2 class="text-3xl font-extrabold mt-4">Restrictions</h2>
                <p>
                    You agree not to, and you will not permit others to:
                </p>
                <div class="pl-0 sm:pl-4">
                    <ul>
                        <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website or make the platform available to any third party.</li>
                        <li>Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website.</li>
                        <li>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of Amaris or its affiliates, partners, suppliers or the licensors of the website.</li>
                    </ul>
                </div>

                <h2 class="text-3xl font-extrabold mt-4">Return and Refund Policy</h2>
                <p>Thanks for shopping at Amaris. We appreciate the fact that you like to buy the stuff we build. We also want to make sure you
                    have a rewarding experience while you’re exploring, evaluating, and purchasing our products.</p>
                <p>As with any shopping experience, there are terms and conditions that apply to transactions at Amaris. We’ll be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase at Amaris, you agree to the
                    terms along with Amaris."’s" Privacy Policy.</p>
                <p>If, for any reason, You are not completely satisfied with any good or service that we provide, don't hesitate to contact us and we will discuss any of the issues you are going through with our product.</p>


                <h2 class="text-3xl font-extrabold mt-4">Your Suggestions</h2>

                <p>
                    Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") provided by you to Amaris with
                    respect to the website shall remain the sole and exclusive property of Amaris.
                </p>
                <p>Amaris shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.
                </p>

                <h2 class="text-3xl font-extrabold mt-4">Your Consent</h2>
                <p>We've updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site
                    and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Terms
                    & Conditions.</p>

                <h2 class="text-3xl font-extrabold mt-4">Links to Other Websites</h2>
                <p>This Terms & Conditions applies only to the Services. The Services may contain links to other websites not operated or
                    controlled by Amaris. We are not responsible for the content, accuracy or opinions expressed in such websites, and such
                    websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use
                    a link to go from the Services to another website, our Terms & Conditions are no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Suchthird parties may use their own cookies or other methods to collect information about you.</p>

                <h2 class="text-3xl font-extrabold mt-4">Cookies</h2>
                <p>Amaris uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on
                    your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our
                    website but are non-essential to their use. However, without these cookies, certain functionality like videos may become
                    unavailable or you would be required to enter your login details every time you visit the website as we would not be able to
                    remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you
                    disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally
                    Identifiable Information in Cookies.</p>
            </div>
        </div>
    </section>
    <!-- end TOS -->
</x-app-layout>
